name = "ClimaAnalysis"
uuid = "29b5916a-a76c-4e73-9657-3c8fd22e65e6"
authors = ["Climate Modelling Alliance <clima-software@caltech.edu>"]
version = "0.1.0"

[deps]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[extensions]
CairoMakieExt = "CairoMakie"

[compat]
NCDatasets = "0.12, 0.13"
OrderedCollections = "1"
Statistics = "1"
julia = "1.9"
