name = "ClimaAnalysis"
uuid = "29b5916a-a76c-4e73-9657-3c8fd22e65e6"
authors = ["Gabriele Bozzola <gbozzola@caltech.edu>"]
version = "0.5.5"

[deps]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"

[extensions]
CairoMakieExt = "CairoMakie"
GeoMakieExt = "GeoMakie"

[compat]
Aqua = "0.8"
CairoMakie = "0.11.11, 0.12"
Documenter = "1"
GeoMakie = "0.6.5"
JuliaFormatter = "1"
NCDatasets = "0.13.1, 0.14"
OrderedCollections = "1.3"
SafeTestsets = "0.1"
Statistics = "1"
Reexport = "1"
Test = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "CairoMakie", "Documenter", "GeoMakie", "JuliaFormatter", "SafeTestsets", "Test"]
