name = "ClimaExplorer"
authors = ["Gabriele Bozzola <gbozzola@caltech.edu>"]
version = "0.0.1"

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ClimaAnalysis = "29b5916a-a76c-4e73-9657-3c8fd22e65e6"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"

[compat]
Bonito = "3"
ClimaAnalysis = "0.5.5"
GeoMakie = "0.6.5, 0.7"
